[supervisord]
nodaemon=true
user=root
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:receiver]
command=uvicorn main:app --host 0.0.0.0 --port %(ENV_RECEIVER_PORT)s --log-level %(ENV_LOG_LEVEL)s
directory=/app/receiver
user=strathon
autostart=true
autorestart=true
startretries=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=PYTHONUNBUFFERED="1"

[program:dashboard]
command=node /app/dashboard/.next/standalone/server.js
directory=/app/dashboard
user=strathon
autostart=true
autorestart=true
startretries=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=PORT="%(ENV_DASHBOARD_PORT)s",HOSTNAME="0.0.0.0"
